project:
  type: website
  output-dir: docs
  render:
    - mp03.qmd

website:
  title: "STA 9750 Submission Material"
  description:
    Course Projects for STA 9750 at Baruch College
  site-url: "https://viktoriaaxelsson.github.io/data-analytics-portfolio/"
  navbar:
    background: primary
    search: false
    
format:
  html:
    theme: <LUX>
    toc: false

editor:
  mode: source
  
  